# Generated by Django 5.0 on 2023-12-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0002_alter_lecture_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=100, verbose_name='Название лекции')),
                ('link', models.URLField(verbose_name='Ссылка на лекцию')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.schedule')),
            ],
        ),
    ]
