# Generated by Django 5.0 on 2023-12-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_lecture_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
            ],
        ),
    ]
