# Generated by Django 5.0 on 2023-12-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('content_type', models.CharField(choices=[('article', 'Статья'), ('video', 'Видеоурок')], default='article', max_length=10, verbose_name='Тип контента')),
                ('link', models.URLField(verbose_name='Ссылка на статью или видеоурок')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
    ]
